---
roles:
  - name: buluma.bootstrap

  - name: geerlingguy.composer

  - name: geerlingguy.apache

  - name: geerlingguy.php

  - name: geerlingguy.pip

  - name: singleplatform-eng.users

  - name: DataDog.datadog

  - name: geerlingguy.nginx

  - name: singleplatform-eng.users

  - name: DataDog.datadog

  - name: geerlingguy.nginx

collections:

  - name: community.crypto

  - name: awx.awx

  - name: ansible.windows

  - name: kubernetes.core

  - name: ansible.utils

  - name: community.docker

  - name: ansible.netcommon

  - name: amazon.aws

  - name: ansible.posix

  - name: community.general

  - name: arista.avd

  - name: borari.pentesting_collection

  - name: dkraklan.terraform_vmware_vm

  - name: sabyadi.zhmc

  - name: itsbryantp.zos_test
  
  - name: ibm.zos_package_manager

  - name: elfelip.keycloak

  - name: joej164.ansible_sample_collection

  - name: jiholland.cisco

  - name: ephracis.doksi
...